# Generated by Django 4.1.12 on 2023-11-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaComponente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('exported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaEquipamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaEntregaComponente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('armazem_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.armazem')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEquipamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaoDeObra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('AD', 'Administrador'), ('FU', 'Funcionário'), ('CL', 'Cliente')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Expedicao',
            fields=[
                ('sent_at', models.DateField(auto_now_add=True)),
                ('truck_license', models.CharField(max_length=50, null=True)),
                ('delivery_date_expected', models.DateField(auto_now_add=True)),
                ('encomenda_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ipv_bd2_projeto.encomendaequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('contribuinte', models.CharField(max_length=50)),
                ('encomenda_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ipv_bd2_projeto.encomendaequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistoProducao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('ended_at', models.DateField(auto_now_add=True)),
                ('armazem_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.armazem')),
                ('equipamento_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.equipamento')),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.utilizador')),
                ('tipo_mao_de_obra_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.tipomaodeobra')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.expedicao')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeGuiaEntregaComponente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.componente')),
                ('guia_entrega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.guiaentregacomponente')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeEncomendaEquipamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.encomendaequipamento')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeEncomendaComponente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.componente')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.encomendacomponente')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeComponenteRegistoProducao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.componente')),
                ('registo_producao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.registoproducao')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.tipodeequipamento'),
        ),
        migrations.AddField(
            model_name='encomendaequipamento',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_encomendaequipamento_set', to='ipv_bd2_projeto.utilizador'),
        ),
        migrations.AddField(
            model_name='encomendaequipamento',
            name='funcionario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionario_encomendaequipamento_set', to='ipv_bd2_projeto.utilizador'),
        ),
        migrations.AddField(
            model_name='encomendacomponente',
            name='fornecedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.fornecedor'),
        ),
        migrations.AddField(
            model_name='encomendacomponente',
            name='funcionario_responsavel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.utilizador'),
        ),
        migrations.AddField(
            model_name='componente',
            name='fornecedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.fornecedor'),
        ),
        migrations.AddConstraint(
            model_name='quantidadeguiaentregacomponente',
            constraint=models.UniqueConstraint(fields=('componente', 'guia_entrega'), name='unique_componente_guia_entrega'),
        ),
        migrations.AddConstraint(
            model_name='quantidadeencomendaequipamento',
            constraint=models.UniqueConstraint(fields=('equipamento', 'encomenda'), name='unique_equipamento_encomenda'),
        ),
        migrations.AddConstraint(
            model_name='quantidadeencomendacomponente',
            constraint=models.UniqueConstraint(fields=('componente', 'encomenda'), name='unique_componente_encomenda'),
        ),
        migrations.AddConstraint(
            model_name='quantidadecomponenteregistoproducao',
            constraint=models.UniqueConstraint(fields=('componente', 'registo_producao'), name='unique_componente_registo_producao'),
        ),
    ]
