# Generated by Django 4.1.12 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ipv_bd2_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilizador_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='password',
            field=models.CharField(default='password', max_length=256),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilizador_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='type',
            field=models.CharField(choices=[('AD', 'Administrador'), ('FU', 'Funcionário'), ('CL', 'Cliente')], default='CL', max_length=2),
        ),
    ]
