# Generated by Django 4.1.12 on 2023-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipv_bd2_projeto', '0002_utilizador_groups_utilizador_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
