# Generated by Django 4.1.12 on 2023-11-29 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipv_bd2_projeto', '0003_utilizador_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
