# Generated by Django 4.1.12 on 2023-12-06 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipv_bd2_projeto', '0005_alter_armazem_id_alter_componente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='encomendacomponente',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='encomendaequipamento',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='delivery_date_expected',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='sent_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guiaentregacomponente',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registoproducao',
            name='ended_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registoproducao',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
