# Generated by Django 4.1.12 on 2023-12-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipv_bd2_projeto', '0006_alter_componente_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registoproducao',
            name='delivery_id',
        ),
        migrations.AddField(
            model_name='expedicao',
            name='registo_producao_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.registoproducao'),
        ),
    ]
