# Generated by Django 4.1.12 on 2023-12-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipv_bd2_projeto', '0007_remove_registoproducao_delivery_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedicao',
            name='registo_producao_id',
        ),
        migrations.AddField(
            model_name='registoproducao',
            name='expedicao_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ipv_bd2_projeto.expedicao'),
        ),
    ]
